package configediter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ian Van Schaick
 */
public class ConfigEditerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConfigEditerGUI
     */
    public ConfigEditerGUI() {
        initComponents();
        // ButtonGroups for Difficulty tab, left side
        compSpdGroup.add(compSpd_VS);
        compSpdGroup.add(compSpd_S);
        compSpdGroup.add(compSpd_M);
        compSpdGroup.add(compSpd_F);
        compSpdGroup.add(compSpd_VF);
        
        constCostGroup.add(constCost_L);
        constCostGroup.add(constCost_M);
        constCostGroup.add(constCost_H);
        
        diffLevelGroup.add(diffLevel_E);
        diffLevelGroup.add(diffLevel_M);
        diffLevelGroup.add(diffLevel_H);
        
        disastersGroup.add(disasters_ON);
        disastersGroup.add(disasters_OFF);
        
        economyGroup.add(economy_SM);
        economyGroup.add(economy_VAR);
        
        industDensGroup.add(industDens_NONE);
        industDensGroup.add(industDens_MIN);
        industDensGroup.add(industDens_VL);
        industDensGroup.add(industDens_L);
        industDensGroup.add(industDens_N);
        industDensGroup.add(industDens_H);
        
        initInterGroup.add(initInter_2);
        initInterGroup.add(initInter_3);
        initInterGroup.add(initInter_4);
        initInterGroup.add(initInter_CUST);
        
        lineReverseGroup.add(lineReverse_TRUE);
        lineReverseGroup.add(lineReverse_FALSE);
        
        buttonGroup9.add(industries_NONE);
        buttonGroup9.add(industries_VL);
        buttonGroup9.add(industries_L);
        buttonGroup9.add(industries_N);
        buttonGroup9.add(industries_H);
        
        //buttonGroups for difficulty tab, right side
        buttonGroup10.add(towns_VL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compSpdGroup = new javax.swing.ButtonGroup();
        constCostGroup = new javax.swing.ButtonGroup();
        diffLevelGroup = new javax.swing.ButtonGroup();
        disastersGroup = new javax.swing.ButtonGroup();
        economyGroup = new javax.swing.ButtonGroup();
        industDensGroup = new javax.swing.ButtonGroup();
        initInterGroup = new javax.swing.ButtonGroup();
        lineReverseGroup = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        compSpd_VS = new javax.swing.JRadioButton();
        compSpd_S = new javax.swing.JRadioButton();
        compSpd_M = new javax.swing.JRadioButton();
        compSpd_VF = new javax.swing.JRadioButton();
        compSpd_F = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        constCost_M = new javax.swing.JRadioButton();
        constCost_L = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        diffLevel_M = new javax.swing.JRadioButton();
        constCost_H = new javax.swing.JRadioButton();
        diffLevel_E = new javax.swing.JRadioButton();
        diffLevel_H = new javax.swing.JRadioButton();
        disasters_OFF = new javax.swing.JRadioButton();
        disasters_ON = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        economy_VAR = new javax.swing.JRadioButton();
        economy_SM = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        industDens_L = new javax.swing.JRadioButton();
        industDens_MIN = new javax.swing.JRadioButton();
        industDens_NONE = new javax.swing.JRadioButton();
        industDens_H = new javax.swing.JRadioButton();
        industDens_VL = new javax.swing.JRadioButton();
        industDens_N = new javax.swing.JRadioButton();
        initInter_4 = new javax.swing.JRadioButton();
        initInter_3 = new javax.swing.JRadioButton();
        initInter_2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lineReverse_FALSE = new javax.swing.JRadioButton();
        lineReverse_TRUE = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        maxLoan_TEXT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        maxComp_TEXT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        industries_N = new javax.swing.JRadioButton();
        industries_VL = new javax.swing.JRadioButton();
        industries_NONE = new javax.swing.JRadioButton();
        industries_H = new javax.swing.JRadioButton();
        industries_L = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        towns_H = new javax.swing.JRadioButton();
        towns_L = new javax.swing.JRadioButton();
        towns_VL = new javax.swing.JRadioButton();
        towns_CUST = new javax.swing.JRadioButton();
        towns_N = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        seas_H = new javax.swing.JRadioButton();
        seas_L = new javax.swing.JRadioButton();
        seas_VL = new javax.swing.JRadioButton();
        seas_CUST = new javax.swing.JRadioButton();
        seas_M = new javax.swing.JRadioButton();
        subsidy_30 = new javax.swing.JRadioButton();
        subsidy_20 = new javax.swing.JRadioButton();
        subsidy_15 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        subsidy_40 = new javax.swing.JRadioButton();
        terrain_H = new javax.swing.JRadioButton();
        terrain_VF = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        terrain_M = new javax.swing.JRadioButton();
        terrain_F = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        townCoun_PER = new javax.swing.JRadioButton();
        townCoun_TOL = new javax.swing.JRadioButton();
        townCoun_HOS = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        vehicleBr_N = new javax.swing.JRadioButton();
        vehicleBr_RED = new javax.swing.JRadioButton();
        vehicleBr_NONE = new javax.swing.JRadioButton();
        vehicleCost_H = new javax.swing.JRadioButton();
        vehicleCost_M = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        vehicleCost_L = new javax.swing.JRadioButton();
        initInter_CUST_Text = new javax.swing.JTextField();
        initInter_CUST = new javax.swing.JRadioButton();
        towns_TEXT = new javax.swing.JTextField();
        seas_TEXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Misc", jPanel1);

        compSpd_VS.setText("very slow");

        compSpd_S.setText("slow");

        compSpd_M.setText("medium");

        compSpd_VF.setText("very fast");

        compSpd_F.setText("fast");

        jLabel9.setText("Competr. speed");

        jLabel10.setText("const. cost");

        constCost_M.setText("medium");

        constCost_L.setText("low");

        jLabel11.setText("diff. level");

        diffLevel_M.setText("medium");

        constCost_H.setText("high");

        diffLevel_E.setText("easy");

        diffLevel_H.setText("hard");

        disasters_OFF.setText("off");

        disasters_ON.setText("on");

        jLabel12.setText("disasters");

        jLabel13.setText("economy");

        economy_VAR.setText("variable");

        economy_SM.setText("smooth");

        jLabel14.setText("indust. density");

        industDens_L.setText("low");

        industDens_MIN.setText("minimal");

        industDens_NONE.setText("none");

        industDens_H.setText("high");

        industDens_VL.setText("very low");

        industDens_N.setText("normal");

        initInter_4.setText("4 %");

        initInter_3.setText("3 %");

        initInter_2.setText("2 %");

        jLabel15.setText("init. interest");

        jLabel16.setText("line reverse mode");

        lineReverse_FALSE.setText("false");

        lineReverse_TRUE.setText("true");

        jLabel17.setText("Max loan (100 000-500 000)");

        maxLoan_TEXT.setText("custom");

        jLabel18.setText("Max # of compet. (0-14)");

        maxComp_TEXT.setText("custom");

        jLabel19.setText("# of industries");

        industries_N.setText("normal");

        industries_VL.setText("very low");

        industries_NONE.setText("none");

        industries_H.setText("high");

        industries_L.setText("low");

        jLabel20.setText("# of towns");

        towns_H.setText("high");

        towns_L.setText("low");

        towns_VL.setText("very low");

        towns_CUST.setText("custom");

        towns_N.setText("normal");

        jLabel21.setText("# of seas / lakes");

        seas_H.setText("high");

        seas_L.setText("low");

        seas_VL.setText("very low");

        seas_CUST.setText("custom");

        seas_M.setText("medium");

        subsidy_30.setText("x 3.0");

        subsidy_20.setText("x 2.0");

        subsidy_15.setText("x 1.5");

        jLabel22.setText("subsidy multilplier");

        subsidy_40.setText("x 4.0");

        terrain_H.setText("hilly");

        terrain_VF.setText("very flat");

        jLabel23.setText("terrain type");

        terrain_M.setText("mountainous");

        terrain_F.setText("flat");

        jLabel24.setText("town council tolerance");

        townCoun_PER.setText("permissive");

        townCoun_TOL.setText("tolerant");

        townCoun_HOS.setText("hostile");

        jLabel25.setText("vehicle breakdowns");

        vehicleBr_N.setText("normal");

        vehicleBr_RED.setText("reduced");

        vehicleBr_NONE.setText("none");

        vehicleCost_H.setText("high");

        vehicleCost_M.setText("medium");

        jLabel26.setText("vehicle cost");

        vehicleCost_L.setText("low");

        initInter_CUST_Text.setText("custom");

        initInter_CUST.setText("custom");

        towns_TEXT.setText("custom");

        seas_TEXT.setText("custom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compSpd_F)
                            .addComponent(compSpd_VS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(compSpd_S)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compSpd_M))
                            .addComponent(compSpd_VF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(industDens_NONE)
                            .addComponent(industDens_L))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(industDens_N)
                            .addComponent(industDens_MIN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(industDens_H)
                            .addComponent(industDens_VL)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(disasters_ON))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(8, 8, 8)
                                .addComponent(economy_SM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(economy_VAR)
                            .addComponent(disasters_OFF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(initInter_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initInter_3))
                            .addComponent(initInter_CUST))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initInter_CUST_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initInter_4)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(maxComp_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maxLoan_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(51, 51, 51))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(industries_N)
                                    .addGap(18, 18, 18)
                                    .addComponent(industries_H))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(industries_NONE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(industries_VL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(industries_L)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineReverse_TRUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineReverse_FALSE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diffLevel_E)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diffLevel_M)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(constCost_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(constCost_M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(constCost_H)
                            .addComponent(diffLevel_H))))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seas_VL)
                            .addComponent(seas_H))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(seas_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seas_M))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(seas_CUST)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seas_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(towns_H)
                            .addComponent(towns_VL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(towns_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(towns_N))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(towns_CUST)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(towns_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terrain_M)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(terrain_VF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(terrain_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(terrain_H))
                            .addComponent(subsidy_40)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(subsidy_15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subsidy_20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subsidy_30))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(townCoun_HOS)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(townCoun_PER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(townCoun_TOL))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleBr_N)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(vehicleBr_NONE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicleBr_RED))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleCost_L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleCost_M)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleCost_H)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(towns_VL)
                                .addComponent(towns_L)
                                .addComponent(towns_N))
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(towns_H)
                                    .addComponent(towns_CUST)
                                    .addComponent(towns_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seas_VL)
                                .addComponent(jLabel21)
                                .addComponent(seas_L)
                                .addComponent(seas_M)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seas_H)
                            .addComponent(seas_CUST)
                            .addComponent(seas_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(subsidy_15)
                            .addComponent(subsidy_20)
                            .addComponent(subsidy_30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subsidy_40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terrain_VF)
                            .addComponent(jLabel23)
                            .addComponent(terrain_F)
                            .addComponent(terrain_H))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terrain_M)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(townCoun_PER)
                            .addComponent(townCoun_TOL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(townCoun_HOS)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(vehicleBr_NONE)
                            .addComponent(vehicleBr_RED))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleBr_N)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(vehicleCost_L)
                            .addComponent(vehicleCost_M)
                            .addComponent(vehicleCost_H)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compSpd_VS)
                            .addComponent(compSpd_S)
                            .addComponent(compSpd_M)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compSpd_F)
                            .addComponent(compSpd_VF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(constCost_L)
                            .addComponent(constCost_M)
                            .addComponent(constCost_H))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(diffLevel_E)
                                                .addComponent(diffLevel_M)
                                                .addComponent(diffLevel_H))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(disasters_ON)
                                            .addComponent(disasters_OFF))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(economy_SM)
                                            .addComponent(economy_VAR))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(industDens_NONE)
                                            .addComponent(jLabel14)
                                            .addComponent(industDens_MIN)
                                            .addComponent(industDens_VL))))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(industDens_L)
                                .addComponent(industDens_N)
                                .addComponent(industDens_H)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(initInter_2)
                            .addComponent(initInter_3)
                            .addComponent(initInter_4))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(initInter_CUST_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initInter_CUST))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lineReverse_TRUE)
                            .addComponent(lineReverse_FALSE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(maxLoan_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(maxComp_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(industries_NONE)
                            .addComponent(industries_VL)
                            .addComponent(industries_L))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(industries_N)
                            .addComponent(industries_H))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Difficulty", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigEditerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigEditerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigEditerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigEditerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigEditerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.ButtonGroup compSpdGroup;
    private javax.swing.JRadioButton compSpd_F;
    private javax.swing.JRadioButton compSpd_M;
    private javax.swing.JRadioButton compSpd_S;
    private javax.swing.JRadioButton compSpd_VF;
    private javax.swing.JRadioButton compSpd_VS;
    private javax.swing.ButtonGroup constCostGroup;
    private javax.swing.JRadioButton constCost_H;
    private javax.swing.JRadioButton constCost_L;
    private javax.swing.JRadioButton constCost_M;
    private javax.swing.ButtonGroup diffLevelGroup;
    private javax.swing.JRadioButton diffLevel_E;
    private javax.swing.JRadioButton diffLevel_H;
    private javax.swing.JRadioButton diffLevel_M;
    private javax.swing.ButtonGroup disastersGroup;
    private javax.swing.JRadioButton disasters_OFF;
    private javax.swing.JRadioButton disasters_ON;
    private javax.swing.ButtonGroup economyGroup;
    private javax.swing.JRadioButton economy_SM;
    private javax.swing.JRadioButton economy_VAR;
    private javax.swing.ButtonGroup industDensGroup;
    private javax.swing.JRadioButton industDens_H;
    private javax.swing.JRadioButton industDens_L;
    private javax.swing.JRadioButton industDens_MIN;
    private javax.swing.JRadioButton industDens_N;
    private javax.swing.JRadioButton industDens_NONE;
    private javax.swing.JRadioButton industDens_VL;
    private javax.swing.JRadioButton industries_H;
    private javax.swing.JRadioButton industries_L;
    private javax.swing.JRadioButton industries_N;
    private javax.swing.JRadioButton industries_NONE;
    private javax.swing.JRadioButton industries_VL;
    private javax.swing.ButtonGroup initInterGroup;
    private javax.swing.JRadioButton initInter_2;
    private javax.swing.JRadioButton initInter_3;
    private javax.swing.JRadioButton initInter_4;
    private javax.swing.JRadioButton initInter_CUST;
    private javax.swing.JTextField initInter_CUST_Text;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.ButtonGroup lineReverseGroup;
    private javax.swing.JRadioButton lineReverse_FALSE;
    private javax.swing.JRadioButton lineReverse_TRUE;
    private javax.swing.JTextField maxComp_TEXT;
    private javax.swing.JTextField maxLoan_TEXT;
    private javax.swing.JRadioButton seas_CUST;
    private javax.swing.JRadioButton seas_H;
    private javax.swing.JRadioButton seas_L;
    private javax.swing.JRadioButton seas_M;
    private javax.swing.JTextField seas_TEXT;
    private javax.swing.JRadioButton seas_VL;
    private javax.swing.JRadioButton subsidy_15;
    private javax.swing.JRadioButton subsidy_20;
    private javax.swing.JRadioButton subsidy_30;
    private javax.swing.JRadioButton subsidy_40;
    private javax.swing.JRadioButton terrain_F;
    private javax.swing.JRadioButton terrain_H;
    private javax.swing.JRadioButton terrain_M;
    private javax.swing.JRadioButton terrain_VF;
    private javax.swing.JRadioButton townCoun_HOS;
    private javax.swing.JRadioButton townCoun_PER;
    private javax.swing.JRadioButton townCoun_TOL;
    private javax.swing.JRadioButton towns_CUST;
    private javax.swing.JRadioButton towns_H;
    private javax.swing.JRadioButton towns_L;
    private javax.swing.JRadioButton towns_N;
    private javax.swing.JTextField towns_TEXT;
    private javax.swing.JRadioButton towns_VL;
    private javax.swing.JRadioButton vehicleBr_N;
    private javax.swing.JRadioButton vehicleBr_NONE;
    private javax.swing.JRadioButton vehicleBr_RED;
    private javax.swing.JRadioButton vehicleCost_H;
    private javax.swing.JRadioButton vehicleCost_L;
    private javax.swing.JRadioButton vehicleCost_M;
    // End of variables declaration//GEN-END:variables
}
